const PDFDocument = require('pdfkit');

const NAVY = '#0a1a3c';
const GOLD = '#d4af37';
const MUTED = '#6b7690';

/**
 * Renders a Report document (device/security/performance) as a PDF buffer.
 * Kept deliberately simple and readable rather than trying to exactly
 * mirror the web dashboard's styling - a report someone prints or emails
 * needs to be legible on paper, not just look nice on a screen.
 */
function generateReportPdf(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // --- Header ---
    doc.fillColor(NAVY).fontSize(20).font('Helvetica-Bold').text('NetGuardian', { continued: true });
    doc.fillColor(GOLD).text('  •');
    doc.moveDown(0.2);
    doc.fillColor(MUTED).fontSize(10).font('Helvetica').text('Network Monitoring & Access Control System');
    doc.moveDown(1);

    doc.fillColor(NAVY).fontSize(16).font('Helvetica-Bold').text(report.title);
    doc.fillColor(MUTED).fontSize(9).font('Helvetica').text(
      `Generated ${new Date(report.createdAt).toLocaleString()}${report.generatedBy ? ` by ${report.generatedBy.name || report.generatedBy.email}` : ''}`
    );
    doc.moveDown(1);
    drawDivider(doc);
    doc.moveDown(1);

    if (report.type === 'device') {
      renderDeviceReport(doc, report.summary);
    } else if (report.type === 'security') {
      renderSecurityReport(doc, report.summary);
    } else if (report.type === 'network_performance') {
      renderPerformanceReport(doc, report.summary);
    }

    // --- Footer ---
    doc.moveDown(2);
    drawDivider(doc);
    doc.fillColor(MUTED).fontSize(8).text('Generated by NetGuardian. This report reflects data at the time of generation.', {
      align: 'center'
    });

    doc.end();
  });
}

function drawDivider(doc) {
  const y = doc.y;
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e7eaf3').lineWidth(1).stroke();
}

function sectionHeading(doc, text) {
  doc.fillColor(NAVY).fontSize(12).font('Helvetica-Bold').text(text);
  doc.moveDown(0.4);
}

function statLine(doc, label, value) {
  doc.fillColor(MUTED).fontSize(9).font('Helvetica').text(label, { continued: true, width: 250 });
  doc.fillColor(NAVY).font('Helvetica-Bold').text(`  ${value}`);
}

function renderDeviceReport(doc, summary) {
  sectionHeading(doc, 'Summary');
  statLine(doc, 'Total Devices', summary.totalDevices);
  statLine(doc, 'Online', summary.byStatus?.online ?? 0);
  statLine(doc, 'Offline', summary.byStatus?.offline ?? 0);
  statLine(doc, 'Authorized', summary.byAuthorization?.authorized ?? 0);
  statLine(doc, 'Unauthorized', summary.byAuthorization?.unauthorized ?? 0);
  statLine(doc, 'Blocked', summary.byAuthorization?.blocked ?? 0);
  statLine(doc, 'Pending', summary.byAuthorization?.pending ?? 0);
  doc.moveDown(1);

  sectionHeading(doc, 'Device Inventory');
  const devices = summary.devices || [];
  if (devices.length === 0) {
    doc.fillColor(MUTED).fontSize(9).text('No devices recorded.');
    return;
  }

  const colX = { ip: 50, hostname: 150, type: 290, status: 360, auth: 430 };
  doc.fontSize(8).font('Helvetica-Bold').fillColor(MUTED);
  doc.text('IP Address', colX.ip, doc.y, { continued: false });
  const headerY = doc.y - 10;
  doc.text('Hostname', colX.hostname, headerY);
  doc.text('Type', colX.type, headerY);
  doc.text('Status', colX.status, headerY);
  doc.text('Auth', colX.auth, headerY);
  doc.moveDown(0.3);
  drawDivider(doc);
  doc.moveDown(0.3);

  doc.font('Helvetica').fillColor(NAVY).fontSize(8);
  devices.slice(0, 60).forEach((d) => {
    const rowY = doc.y;
    if (rowY > 760) {
      doc.addPage();
    }
    const y = doc.y;
    doc.text(d.ip || '-', colX.ip, y, { width: 95 });
    doc.text(d.hostname || 'Unknown', colX.hostname, y, { width: 135 });
    doc.text(d.type || '-', colX.type, y, { width: 65 });
    doc.text(d.status || '-', colX.status, y, { width: 65 });
    doc.text(d.authorization || '-', colX.auth, y, { width: 100 });
    doc.moveDown(0.6);
  });

  if (devices.length > 60) {
    doc.moveDown(0.5);
    doc.fillColor(MUTED).fontSize(8).text(`...and ${devices.length - 60} more devices (see full list in the app).`);
  }
}

function renderSecurityReport(doc, summary) {
  sectionHeading(doc, 'Summary');
  statLine(doc, 'Suspicious/Unauthorized Devices', summary.suspiciousDeviceCount ?? 0);
  statLine(doc, 'Total Alerts (last 100)', summary.totalAlerts ?? 0);
  statLine(doc, 'Unresolved Alerts', summary.unresolvedAlerts ?? 0);
  doc.moveDown(0.6);

  sectionHeading(doc, 'Alert Severity Breakdown');
  const sev = summary.severityBreakdown || {};
  statLine(doc, 'Critical', sev.critical ?? 0);
  statLine(doc, 'High', sev.high ?? 0);
  statLine(doc, 'Medium', sev.medium ?? 0);
  statLine(doc, 'Low', sev.low ?? 0);
  doc.moveDown(1);

  sectionHeading(doc, 'Suspicious / Unauthorized Devices');
  const devices = summary.suspiciousDevices || [];
  if (devices.length === 0) {
    doc.fillColor(MUTED).fontSize(9).text('None currently flagged.');
    return;
  }
  doc.font('Helvetica').fillColor(NAVY).fontSize(8);
  devices.slice(0, 60).forEach((d) => {
    if (doc.y > 760) doc.addPage();
    doc.text(`${d.ip}  (${d.mac})  -  ${d.authorization}  -  last seen ${new Date(d.lastSeen).toLocaleString()}`);
    doc.moveDown(0.4);
  });
}

function renderPerformanceReport(doc, summary) {
  sectionHeading(doc, 'Network Performance');
  statLine(doc, 'Devices Monitored', summary.totalDevicesMonitored ?? 0);
  statLine(doc, 'Average Response Time', `${summary.averageResponseTimeMs ?? 0} ms`);
  statLine(doc, 'Recent Scans Logged', summary.recentScans ?? 0);
  statLine(doc, 'Offline Rate', `${summary.offlineRate ?? 0}%`);
}

module.exports = { generateReportPdf };
